apiVersion: v1
kind: ConfigMap
metadata:
  name: archivement-manager-config
  namespace: kube-system
data:
  service-conf: |
    config:
      hostname: "archivement-manager.npool.top"
      http_port: 50340
      grpc_port: 50341
      healthz_port: 50342
      prometheus_port: 50343
      appid: "89089012783789789719823798127398"
      serviceid: "6161ecc0-0b2c-11ed-b571-72e9de4b20f6"
      logdir: "./"
      apolloAccessKey: "0147fb70b815403790e8634b899fac07"
